name: Deploy Production

on:
  push:
  workflow_dispatch:
      inputs:
        beta:
            type: boolean
            default: false
            description: Deploy to Beta
        origin:
            type: boolean
            default: false
            description: Deploy to Origin
        alpha:
            type: boolean
            default: false
            description: Deploy to Alpha
        production:
            type: boolean
            default: false
            description: Deploy to Production
        environment:
            description: 'Environment to run deploy'
            type: environment
            default: production

jobs:

#  set-analytics:
#    runs-on: ubuntu
#    outputs:
#        analytics: ${{ steps.step1.outputs.analytics }}
#    steps:
#      - id: step1
#        run: |
#          echo "{
#            \"beta\": ${{ toJson(github.event.inputs.beta) }},
#            \"origin\": ${{ toJson(github.event.inputs.origin) }},
#            \"alpha\": ${{ toJson(github.event.inputs.alpha) }},
#            \"production\": ${{ toJson(github.event.inputs.production) }}
#          }" > output.json
#          echo "analytics=$( jq -c 'map_values(. // empty) | keys' output.json)" >> $GITHUB_OUTPUT
#
#  check-build:
#    runs-on: ubuntu
#    steps:
#        - name: Echo
#          run: |
#            echo ${{ toJson(github.event.inputs.production) }}
#            echo ${{ toJson(github) }}
#
#
#  build:
#    runs-on: ubuntu
#    if: failure()
#    needs: check-build
#    name: build-${{ matrix.app-env }}
#    strategy:
#      matrix:
#        app-env: ['staging', 'production']
#    steps:
#        - name: TEst
#          run: echo "Build RUN ${{ matrix.app-env }}"
  soos_sast_scan:
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SOOS SAST Scan
        uses: soos-io/soos-sast-github-action@v1
        with:
          client_id: rfwribqyt
          api_key: NGM2NDcxZWMtZTJlNi00OGJmLWE0YjctODA1MzNiM2I5NjQ4
          project_name: ${{ github.repository }}

  soos_dast_scan:
    name: SOOS DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Scan
        uses: soos-io/soos-dast-github-action@v2
        with:
          client_id: rfwribqyt
          api_key: NGM2NDcxZWMtZTJlNi00OGJmLWE0YjctODA1MzNiM2I5NjQ4
          project_name: "SOOS-DAST-Scan"
          target_url: "https://master-gusa-desktop.gusadev.com"


  deployment:
    runs-on: ubuntu
    name: deploy-${{ matrix.analytics }}
    if: ${{ needs.build.result == 'skipped' || needs.build.result == 'success' || needs.build.result == null }}
    needs: [ soos_dast_scan ]
    strategy:
        matrix:
           analytics: ${{ fromJSON(needs.set-analytics.outputs.analytics) }}
    steps:
        - name: Echo
          run: echo "${{ matrix.analytics }}"


  deploy-stable-release-2:
    runs-on: ubuntu
    name: ${{ matrix.host }}-deploy
    needs: deployment
    strategy:
        matrix:
          host: [ release-2, stable ]
          isStable:
            - ${{ contains(inputs.origin, 'false') }}
          exclude:
            - isStable: false
              host: "stable"
    steps:
        - name: Run Deploy
          run: |
            echo '${{ matrix.host }}'